# Pegar las marcas

In [35]:
import os
import pandas as pd
import numpy as np
import datetime

In [11]:
os.chdir('/Users/santiagoherreragarcia/OneDrive - Universidad de los Andes/Semestre 2022-1/Machine Learning/Trabajo Final/Data')
dfs=[]
for d in os.listdir():
    if 'Marcas' in d: 
        df=pd.read_pickle(d)
        dfs.append(df)

In [12]:
marcas=pd.concat(dfs)
marcas.drop(columns=['cap'], inplace=True)

In [13]:
marcas.columns=['Author ID','bot']

In [14]:
marcas.dropna(inplace=True)
marcas.to_pickle('Y Botometer.pkl')

In [18]:
##Main characteristics:
main_characteristics=pd.read_pickle('Consolidated_V0.pkl')

In [20]:
pd.set_option('display.max_columns', None)
main_characteristics.head()

,ID,Permalink,Author ID,Author Name,Author Location,Author Description,Author Followers,Author Following,Author Tweets,Author Profile Image,Author Verified,Date,Text,Replies,Retweets,Favorites,Quotes,is Retweet?,Reply To User Name,Mentions,Referenced Tweet,Reference Type,Referenced Tweet Author ID,Media URLs,Media Keys
0,1529541764843028484,/mdcs87/status/1529541764843028484,252912120,mdcs87,"Bucaramanga, Colombia",Historia geograf√≠a y deportes.\nOrgulloso egre...,1016,1563,16033,https://pbs.twimg.com/profile_images/131429828...,False,2022/05/25 14:15:48,@roots360co @AdrianaRudling No s√© lo de presen...,0,0,0,0,False,roots360co,roots360co AdrianaRudling,1.529509e+18,replied_to,1.261858e+18,NaN,NaN
1,1529453075819282433,/mdcs87/status/1529453075819282433,252912120,mdcs87,"Bucaramanga, Colombia",Historia geograf√≠a y deportes.\nOrgulloso egre...,1016,1563,16033,https://pbs.twimg.com/profile_images/131429828...,False,2022/05/25 08:23:23,RT @PettinaVanni: Juntos con @CEHColmex @UNAM_...,0,1,0,0,True,NaN,PettinaVanni CEHColmex UNAM_Historicas CideHi...,1.529453e+18,retweeted,1.235728e+18,NaN,NaN
2,1529452371662852097,/mdcs87/status/1529452371662852097,252912120,mdcs87,"Bucaramanga, Colombia",Historia geograf√≠a y deportes.\nOrgulloso egre...,1016,1563,16033,https://pbs.twimg.com/profile_images/131429828...,False,2022/05/25 08:20:35,RT @laurarovi1: Una nueva masacre con armas en...,0,2,0,0,True,NaN,laurarovi1,1.529452e+18,retweeted,7.155651e+17,NaN,NaN
3,1529448991611658240,/mdcs87/status/1529448991611658240,252912120,mdcs87,"Bucaramanga, Colombia",Historia geograf√≠a y deportes.\nOrgulloso egre...,1016,1563,16033,https://pbs.twimg.com/profile_images/131429828...,False,2022/05/25 08:07:10,RT @Toni_Padilla: Esto. Steve Kerr. ‚úäüèº https:/...,0,3,0,0,True,NaN,Toni_Padilla,1.529381e+18,retweeted,1.922814e+08,NaN,NaN
4,1529302053125758977,/mdcs87/status/1529302053125758977,252912120,mdcs87,"Bucaramanga, Colombia",Historia geograf√≠a y deportes.\nOrgulloso egre...,1016,1563,16033,https://pbs.twimg.com/profile_images/131429828...,False,2022/05/24 22:23:17,RT @laquintana2015: Si te habla de anticorrupc...,0,42,0,0,True,NaN,laquintana2015,1.529251e+18,retweeted,4.206114e+09,NaN,NaN

In [22]:
user_juancho=pd.read_pickle('user_model_Profile_Caracteristics.pkl')

In [23]:
user_juancho.head()

,User Name,ID,Author Followers,Author Following,Author Tweets,Author Verified,Tweet Replies,Tweet Retweets,Tweet Favorites,Tweet Quotes,TweetFeature First Date,TweetFeature Last Date,TweetFeature Date,Tweets Numbers,TweetFeature Multimedia,TweetFeature Retweet,TweetFeature Quoted,TweetFeature Reply,TweetFeature MentionRelevant UserName,TweetFeature Distance Between Tweets (mean),TweetFeature Distance Between Tweets (sd)
0,Efectoresidual,307622640,1088.0,1218.0,52890.0,0.0,0.000000,2593.710000,0.000000,0.000000,2022-05-20 14:52:11,2022-05-25 11:44:26,2022-05-23 02:24:36.480000000,100,0.300000,0.950000,0.02,0.030000,0.650000,0 days 01:10:49.848484848,8.486716e+12
1,sivanxregui,334962348,2986.0,2619.0,138824.0,0.0,0.140000,2826.330000,0.370000,0.000000,2022-05-22 20:05:35,2022-05-25 14:20:24,2022-05-24 10:50:16.070000128,100,0.380000,0.520000,0.14,0.120000,0.060000,0 days 00:40:08.979797979,6.099901e+12
2,educalibertad,534042878,4351.0,3025.0,49136.0,0.0,0.030303,512.090909,0.222222,0.010101,2022-05-24 04:36:00,2022-05-25 14:11:24,2022-05-24 22:39:24.484848384,99,0.323232,0.929293,0.00,0.060606,0.030303,0 days 00:20:33.918367346,3.896708e+12
3,Grimberlaing,2347196220,260.0,240.0,12336.0,0.0,0.000000,2275.010000,0.000000,0.000000,2022-05-17 13:09:26,2022-05-25 08:22:58,2022-05-23 07:30:10.050000128,100,0.160000,0.980000,0.00,0.020000,0.750000,0 days 01:53:28.202020202,2.427060e+13
4,yoluchomucho,267284883,18190.0,2438.0,59172.0,0.0,0.320000,970.980000,10.780000,0.050000,2022-05-16 13:08:56,2022-05-25 11:48:50,2022-05-21 10:19:14.449999872,100,0.290000,0.750000,0.09,0.090000,0.460000,0 days 02:10:06,1.540682e+13

In [30]:
#Issue
user_juancho['TweetFeature Distance Between Tweets (sd)']=user_juancho['TweetFeature Distance Between Tweets (mean)'].apply(lambda x: x.seconds)

In [31]:
user_juancho.head()

,User Name,ID,Author Followers,Author Following,Author Tweets,Author Verified,Tweet Replies,Tweet Retweets,Tweet Favorites,Tweet Quotes,TweetFeature First Date,TweetFeature Last Date,TweetFeature Date,Tweets Numbers,TweetFeature Multimedia,TweetFeature Retweet,TweetFeature Quoted,TweetFeature Reply,TweetFeature MentionRelevant UserName,TweetFeature Distance Between Tweets (mean),TweetFeature Distance Between Tweets (sd)
0,Efectoresidual,307622640,1088.0,1218.0,52890.0,0.0,0.000000,2593.710000,0.000000,0.000000,2022-05-20 14:52:11,2022-05-25 11:44:26,2022-05-23 02:24:36.480000000,100,0.300000,0.950000,0.02,0.030000,0.650000,0 days 01:10:49.848484848,4249
1,sivanxregui,334962348,2986.0,2619.0,138824.0,0.0,0.140000,2826.330000,0.370000,0.000000,2022-05-22 20:05:35,2022-05-25 14:20:24,2022-05-24 10:50:16.070000128,100,0.380000,0.520000,0.14,0.120000,0.060000,0 days 00:40:08.979797979,2408
2,educalibertad,534042878,4351.0,3025.0,49136.0,0.0,0.030303,512.090909,0.222222,0.010101,2022-05-24 04:36:00,2022-05-25 14:11:24,2022-05-24 22:39:24.484848384,99,0.323232,0.929293,0.00,0.060606,0.030303,0 days 00:20:33.918367346,1233
3,Grimberlaing,2347196220,260.0,240.0,12336.0,0.0,0.000000,2275.010000,0.000000,0.000000,2022-05-17 13:09:26,2022-05-25 08:22:58,2022-05-23 07:30:10.050000128,100,0.160000,0.980000,0.00,0.020000,0.750000,0 days 01:53:28.202020202,6808
4,yoluchomucho,267284883,18190.0,2438.0,59172.0,0.0,0.320000,970.980000,10.780000,0.050000,2022-05-16 13:08:56,2022-05-25 11:48:50,2022-05-21 10:19:14.449999872,100,0.290000,0.750000,0.09,0.090000,0.460000,0 days 02:10:06,7806

In [52]:
keep_vars=['ID', 'Author Followers', 
           'Author Following', 'Author Tweets', 
           'Author Verified', 'Tweet Replies', 'Tweet Retweets', 'Tweet Favorites', 
          'Tweet Quotes', 'TweetFeature First Date', 'TweetFeature Last Date',
           'TweetFeature Multimedia', 'TweetFeature Retweet','TweetFeature Quoted',
           'TweetFeature Reply','TweetFeature MentionRelevant UserName',
           'TweetFeature Distance Between Tweets (sd)', ]
user_juancho=user_juancho.loc[:,keep_vars]
user_juancho.rename(columns={'ID':'Author ID'}, inplace=True)

In [64]:
user_juancho['TweetFeature First Date']=user_juancho['TweetFeature First Date'].apply(lambda x: x.timestamp())
user_juancho['TweetFeature Last Date']=user_juancho['TweetFeature Last Date'].apply(lambda x: x.timestamp())
user_juancho['Author ID']=user_juancho['Author ID'].astype(str)

In [65]:
user_juancho.to_pickle('model_characteristics.pkl')

In [56]:
#Juandi

In [61]:
user_juandi=pd.read_pickle('user_model_spacy.pkl')

AttributeError: Can't get attribute '_unpickle_block' on <module 'pandas._libs.internals' from '/Users/santiagoherreragarcia/opt/anaconda3/lib/python3.8/site-packages/pandas/_libs/internals.cpython-38-darwin.so'>